### ISSUE TITLE
What version of Telegram-FOSS is relevant for patch? 

### ISSUE THREAD

**Issue by askucher** [nebula-chat/clients#3]
As far as I know, FOSS uses the latest version of the protocol. what version should we patch?

from readme
```md
Get Telegram-FOSS source code

patch

build, see build Telegram-FOSS, and google
```

**Comment by wubenqi** [comment]
a655fde98089ad949f1d131cb6d627d70bb5159e

**Comment by askucher** [comment]
we did not find commit a655fde98089ad949f1d131cb6d627d70bb5159e there.

Do you have a link on right repo?

**Comment by wubenqi** [comment]
commit a655fde98089ad949f1d131cb6d627d70bb5159e (HEAD -> master, origin/master, origin/HEAD)
Author: thermatk <thermatk@thermatk.com>
Date:   Thu Sep 6 08:10:11 2018 +0300

    [TF] Readme + Changelog

commit a274ced7c2e566d8516e1b985fd268c4bab0ba1b
Author: thermatk <thermatk@thermatk.com>
Date:   Tue Jul 31 11:18:43 2018 +0200

    [TF][FEATURE] force Telegram's static map previews

**Comment by wubenqi** [comment]
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/tree/a655fde98089ad949f1d131cb6d627d70bb5159e

**Comment by askucher** [comment]
Thank you. Looking forward to contribute  ;)
