### ISSUE TITLE
compile tdesktop Linux 

### ISSUE THREAD

**Issue by stdanley** [nebula-chat/clients#4]
我在尝试编译tdesktop， 根据官方指南，编译tdesktop时，先要用tdesktop/telegram下的configure.sh产生makefile。
但nebula要求checkout特定的version，checkout该版本时，configure.sh就没有了，
请问作者如何编译的？

**Comment by wubenqi** [comment]
参考指定版本的编译文档

**Comment by stdanley** [comment]
ok，看到了，在docs有特定版本的编译说明，谢谢
