### ISSUE TITLE
老版本客户端的开发环境

### ISSUE THREAD

**Issue by ChenMoGe2** [nebula-chat/clients#6]
请问这个老版本的开发环境建议使用什么，我看这个版本的readme里没有，是要用最新的开发环境配置吗
我目前的配置
Android Studio:4.1.3
Os:WIN 10
Ndk:r20
targetSdkVersion:30
minSdkVersion:29
这个配置很多地方都有报错，能麻烦成功的同学发下自己的配置吗

**Comment by wubenqi** [comment]
用2018年底的开发环境

**Comment by ChenMoGe2** [comment]
@wubenqi 好的，谢谢
